<?php
use Magento\Framework\App\Action\Action;
const PARAM_NAME_BASE64_URL = 'r64';
const PARAM_NAME_URL_ENCODED = 'uenc';
$productCollection = $block->getProductCollection();
 if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
 ?>
<?php if ($block->customerLoggedIn()) : ?>
<?php if (!$productCollection->count()) : ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')); ?></div></div>
<?php else :?>
<?= $block->getToolbarHtml() ?>
<div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
    <ol class="products list items product-items">
        <?php
        $priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
        foreach ($productCollection as $product) {
             $postParams = $block->getAddToCartPostParams($product);
            ?>
            <li class="item product product-item">                
                <div class="product-item-info" data-container="product-grid">
                <a href="<?= $product->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">

                    <span class="product-image-container" style="width:240px;">
                        <span class="product-image-wrapper" style="padding-bottom: 125%;">
                            <img class="product-image-photo" src="<?= $this->getImage($product); ?>" width="240" height="300" alt="t-shirt Man">
                            <!-- <img class="product-image-photo" src="<?= $this->getUrl().'pub/media/catalog/product'.$product->getImage(); ?>" width="240" height="300" alt="t-shirt Man"> -->
                        </span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php echo  $product->getProductUrl(); ?>">
                                <?php echo $product->getName()."</br>";?> 
                                <?php echo "<b>"."SKU"."</b>"." :".$product->getSku();?> 
                            </a>
                        </strong>
                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="2">


                            <span class="price-container price-final_price tax weee">
                                <span id="product-price-2" data-price-amount="20" data-price-type="finalPrice" class="price-wrapper ">
                                    <span class="price"><?php echo $priceHelper->currency($product->getFinalPrice(), true, false); ?></span>    </span>
                                </span>
						</div>      
						<?php if($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
							$swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Multiunique_Productlist::renderer.phtml");
							   echo $swatchBlock->setProduct($product)->toHtml();
							} 
						?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <form data-role="tocart-form" id="addform" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
										<button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    </form> 
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                     <?php } ?>
                </li>  
        </ol>
        </div>
        <?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
            "product_sku": "<?= $block->escapeJs($product->getSku()) ?>"
        }
    }
}
</script>
<?php endif; ?>